// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hnbvjbytlovbxcsqbrrf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhuYnZqYnl0bG92Ynhjc3FicnJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MzEzMTUsImV4cCI6MjA3MDQwNzMxNX0.jZzbWqjzFGclniZcEp5VJp0bl8xrF3XiRT77wb2xG5M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});